[features]
seeds = false
skip-lint = false
[programs.devnet]
prediction_market = "BWA61yMRz3bmhvAo7ZKVEcp38cXuBBcnVDpPQx5hMCoY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/lupin/.config/solana/Wallet/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
