[features]
seeds = false
skip-lint = false
[programs.devnet]
prediction_market = "aikiSUtSCAnjnQe5TVyhKX33bMABjzFDzixPVP6B6AA"
spl_minter = "7Lqrekxb2ng3BRU5q4h4JJSCDqZs7ATBMimSYAJLJwEs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/lupin/.config/solana/Wallet/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
